-- QUESTION 1
CREATE TABLE TEST.PUBLIC.EMPLOYEE
    (ID BIGINT NOT NULL,
     NAME VARCHAR(50) NOT NULL,
     BIRTHDAY DATE,
     EMAIL VARCHAR(100));

-- QUESTION 2
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (1, 'Carny', 'cmattaser0@ibm.com', '11/20/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (2, 'North', 'nrooke1@devhub.com', '7/31/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (3, 'Ulrika', 'ufilchagin2@icio.us', '6/1/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (4, 'Hyman', 'hweiser3@un.org', '12/22/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (5, 'Emilia', 'ecowdrey4@flickr.com', '1/22/2022');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (6, 'Tomlin', 'tdash5@a8.net', '4/21/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (7, 'Lilian', 'lgossage6@mozilla.org', '12/27/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (8, 'Kassandra', 'kadame7@exblog.jp', '4/16/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (9, 'Sheryl', 'skirsche8@blinklist.com', '8/9/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (10, 'Alidia', 'akleinholz9@gov.uk', '12/28/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (11, 'Marty', 'mbalchena@ustream.tv', '4/13/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (12, 'Ford', 'fhavercroftb@businesswire.com', '1/30/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (13, 'Claudelle', 'cleemanc@wix.com', '10/31/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (14, 'Susy', 'swipperd@netlog.com', '4/2/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (15, 'Pennie', 'pdewsnape@homestead.com', '9/30/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (16, 'Haley', 'hrutherfordf@yellowbook.com', '2/28/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (17, 'Julio', 'jlumsdaleg@tinyurl.com', '11/23/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (18, 'Amalle', 'ajeynessh@cloudflare.com', '4/19/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (19, 'Saw', 'stilli@webeden.co.uk', '7/15/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (20, 'Ardine', 'amacloughlinj@adobe.com', '8/10/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (21, 'Kipp', 'kstoggellk@si.edu', '9/8/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (22, 'Phelia', 'pgilcriestl@mac.com', '7/10/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (23, 'Mata', 'mharvardm@rambler.ru', '6/27/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (24, 'Delcina', 'dflattn@ft.com', '12/15/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (25, 'Jeffy', 'jsellwoodo@bravesites.com', '6/2/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (26, 'Doralyn', 'dbellisp@qq.com', '11/10/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (27, 'Judon', 'jmascallq@ebay.co.uk', '3/14/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (28, 'Margi', 'mespositor@cam.ac.uk', '12/23/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (29, 'Malia', 'mdulwitchs@indiatimes.com', '2/20/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (30, 'Anton', 'arobesont@domainmarket.com', '3/25/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (31, 'Marley', 'mokeevanu@instagram.com', '8/5/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (32, 'Mack', 'mrasorv@imgur.com', '9/16/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (33, 'Susy', 'smauricew@nps.gov', '5/12/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (34, 'Allina', 'aesomex@themeforest.net', '1/28/2022');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (35, 'Octavia', 'oandriessey@photobucket.com', '7/28/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (36, 'Marv', 'mduffinz@stanford.edu', '1/1/2022');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (37, 'Solly', 'sdoeg10@mayoclinic.com', '5/14/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (38, 'Marcie', 'mgurery11@howstuffworks.com', '8/21/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (39, 'Katleen', 'kbenzie12@clickbank.net', '9/18/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (40, 'Bryna', 'blynskey13@java.com', '3/19/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (41, 'Noah', 'nwahlberg14@sitemeter.com', '5/10/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (42, 'Thoma', 'tgiorgini15@yelp.com', '10/8/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (43, 'Elora', 'edoumenc16@dyndns.org', '7/8/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (44, 'Homerus', 'hmatyja17@jimdo.com', '9/5/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (45, 'Roxane', 'rbirmingham18@i2i.jp', '11/14/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (46, 'Buddie', 'bmerrisson19@aboutads.info', '3/1/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (47, 'Xenia', 'xsmeaton1a@google.ca', '10/24/2021');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (48, 'Silvain', 'sisakovitch1b@bloglovin.com', '2/14/2020');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (49, 'Duane', 'dranns1c@weather.com', '2/27/2022');
insert into TEST.PUBLIC.EMPLOYEE (id, name, email, birthday) values (50, 'Thayne', 'tdishman1d@unc.edu', '2/16/2020');

-- QUESTION 3
UPDATE TEST.PUBLIC.EMPLOYEE
    SET NAME = 'Ronald Reagan'
    WHERE ID = 40;
UPDATE TEST.PUBLIC.EMPLOYEE
    SET EMAIL = 'woodrow.wilson@wh.gov.us'
    WHERE ID = 28;
UPDATE TEST.PUBLIC.EMPLOYEE
    SET BIRTHDAY = '04/08/1961'
    WHERE ID = 44;
UPDATE TEST.PUBLIC.EMPLOYEE
    SET NAME = 'Abraham Lincoln'
    WHERE ID = 16;
UPDATE TEST.PUBLIC.EMPLOYEE
    SET EMAIL = 'harry.truman@wh.gov.us'
    WHERE ID = 33;

-- QUESTION 4
DELETE FROM TEST.PUBLIC.EMPLOYEE
    WHERE ID = 45;
DELETE FROM TEST.PUBLIC.EMPLOYEE
    WHERE ID = 41;
DELETE FROM TEST.PUBLIC.EMPLOYEE
    WHERE ID = 42;
DELETE FROM TEST.PUBLIC.EMPLOYEE
    WHERE ID = 35;
DELETE FROM TEST.PUBLIC.EMPLOYEE
    WHERE ID = 37;