-- First Question
SELECT TITLE,DESCRIPTION FROM dvdrental.public.film;

-- Second Question
SELECT * FROM dvdrental.public.film WHERE LENGTH > 60 AND LENGTH < 75;

-- Third Question
SELECT * FROM dvdrental.public.film WHERE RENTAL_RATE = 0.99 AND (REPLACEMENT_COST = 12.99 OR REPLACEMENT_COST = 28.99);

-- Fourth Question
SELECT LAST_NAME FROM DVDRENTAL.PUBLIC.CUSTOMER WHERE FIRST_NAME = 'Mary';

-- Fifth Question
SELECT * FROM DVDRENTAL.PUBLIC.FILM WHERE LENGTH <= 50 AND NOT (RENTAL_RATE = 2.99 OR RENTAL_RATE = 4.99);